FileVersion = 1
Dependencies = {corlib = "*", Automate = "*", LybCL = "*"}

[Project]
Name = "AutomateCl"
StartupObject = "AutomateCl.Program"

[Platform.Windows]
Description = "A scripting language"
Company = "Booklordofthedings"
Copyright = "Booklordofthedings"
ProductVersion = "1.0.0"

[Configs.Debug.Win32]
TargetName = "automate"

[Configs.Debug.Win64]
TargetName = "automate"

[Configs.Release.Win32]
TargetName = "automate"

[Configs.Release.Win64]
TargetName = "automate"

[Configs.Paranoid.Win32]
TargetName = "automate"

[Configs.Paranoid.Win64]
TargetName = "automate"

[Configs.Test.Win32]
TargetName = "automate"

[Configs.Test.Win64]
TargetName = "automate"
